# Site
name: 'killerkenobi.io'
description: 'Space for me to share my thoughts on DevOps, Security, and various tech topics.'
logo: 'assets/images/killerkenobi.ico'
favicon: 'assets/images/killerkenobi.ico'
baseurl: '/killerkenobi.github.io'
# disqus: 'demowebsite'
email:

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Anthony:
      name: Anthony
      avatar: /assets/images/killerkenobi.ico
      bio: "Hi, I'm Anthony, the author of this blog. Have a read through my articles and share some feedback. Thanks for reading!"
      email: fake@email.com
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Anthony
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]